sudo: false
cache: bundler
language: ruby
rvm:
  - 2.3.3
env:
  matrix:
    - SOLIDUS_BRANCH=v1.3 DB=mysql
    - SOLIDUS_BRANCH=v1.4 DB=mysql
    - SOLIDUS_BRANCH=v2.0 DB=mysql
    - SOLIDUS_BRANCH=v2.1 DB=mysql
    - SOLIDUS_BRANCH=v2.1 DB=mysql
    - SOLIDUS_BRANCH=v2.2 DB=mysql
    - SOLIDUS_BRANCH=v2.3 DB=mysql
    - SOLIDUS_BRANCH=v2.4 DB=mysql
    - SOLIDUS_BRANCH=v2.5 DB=mysql
    - SOLIDUS_BRANCH=v1.3 DB=postgresql
    - SOLIDUS_BRANCH=v1.4 DB=postgresql
    - SOLIDUS_BRANCH=v2.0 DB=postgresql
    - SOLIDUS_BRANCH=v2.1 DB=postgresql
    - SOLIDUS_BRANCH=v2.2 DB=postgresql
    - SOLIDUS_BRANCH=v2.3 DB=postgresql
    - SOLIDUS_BRANCH=v2.4 DB=postgresql
    - SOLIDUS_BRANCH=v2.5 DB=postgresql
