require 'active_support/deprecation'
require 'sass/rails'
require 'deface'
require 'solidus_core'
require 'solidus_volume_pricing/engine'
require 'solidus_volume_pricing/version'
require 'solidus_volume_pricing/range_from_string'
require 'coffee_script'
